name: 'Build JNI'
description: 'Builds the JNI Native library'
inputs: 
  architecture:
    description: 'The CPU architecture for which to build the lib'
    required: true
  variant:
    description: 'The library type to build'
    required: true
  target-os:
    description: 'The target Operating system identifier'
    required: true

runs:
  using: "composite"
  steps: 
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/download-artifact@v3
      with:
        path: dist

    - id: build-info
      run: |
        if [ ${{ runner.os }} != 'Windows' ]; then
          echo "script=build" >> "$GITHUB_OUTPUT"
          echo "shell=bash" >> "$GITHUB_OUTPUT"
        else
          echo "script=./build.cmd" >> "$GITHUB_OUTPUT"
          echo "shell=pwsh" >> "$GITHUB_OUTPUT"
        fi
      shell: bash

    - run: ${{ steps.build-info.outputs.script }} LibAlphaSkiaJni --target-os ${{ inputs.target-os }} --architecture ${{ inputs.architecture }} --variant ${{ inputs.variant }}
      shell: ${{ steps.build-info.outputs.shell }}

    - uses: actions/upload-artifact@v3
      with:
        name: alphaskia-${{ inputs.target-os }}-jni-${{ inputs.architecture }}-${{ inputs.variant }}
        path: artifacts

