/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alphaTab_alphaSkia_AlphaSkiaTextMetrics */

#ifndef _Included_alphaTab_alphaSkia_AlphaSkiaTextMetrics
#define _Included_alphaTab_alphaSkia_AlphaSkiaTextMetrics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaTextMetrics
 * Method:    getWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_alphaTab_alphaSkia_AlphaSkiaTextMetrics_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaTextMetrics
 * Method:    getActualBoundingBoxLeft
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_alphaTab_alphaSkia_AlphaSkiaTextMetrics_getActualBoundingBoxLeft
  (JNIEnv *, jobject);

/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaTextMetrics
 * Method:    getActualBoundingBoxRight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_alphaTab_alphaSkia_AlphaSkiaTextMetrics_getActualBoundingBoxRight
  (JNIEnv *, jobject);

/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaTextMetrics
 * Method:    getFontBoundingBoxAscent
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_alphaTab_alphaSkia_AlphaSkiaTextMetrics_getFontBoundingBoxAscent
  (JNIEnv *, jobject);

/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaTextMetrics
 * Method:    getFontBoundingBoxDescent
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_alphaTab_alphaSkia_AlphaSkiaTextMetrics_getFontBoundingBoxDescent
  (JNIEnv *, jobject);

/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaTextMetrics
 * Method:    getActualBoundingBoxAscent
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_alphaTab_alphaSkia_AlphaSkiaTextMetrics_getActualBoundingBoxAscent
  (JNIEnv *, jobject);

/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaTextMetrics
 * Method:    getActualBoundingBoxDescent
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_alphaTab_alphaSkia_AlphaSkiaTextMetrics_getActualBoundingBoxDescent
  (JNIEnv *, jobject);

/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaTextMetrics
 * Method:    getEmHeightAscent
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_alphaTab_alphaSkia_AlphaSkiaTextMetrics_getEmHeightAscent
  (JNIEnv *, jobject);

/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaTextMetrics
 * Method:    getEmHeightDescent
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_alphaTab_alphaSkia_AlphaSkiaTextMetrics_getEmHeightDescent
  (JNIEnv *, jobject);

/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaTextMetrics
 * Method:    getHangingBaseline
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_alphaTab_alphaSkia_AlphaSkiaTextMetrics_getHangingBaseline
  (JNIEnv *, jobject);

/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaTextMetrics
 * Method:    getAlphabeticBaseline
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_alphaTab_alphaSkia_AlphaSkiaTextMetrics_getAlphabeticBaseline
  (JNIEnv *, jobject);

/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaTextMetrics
 * Method:    getIdeographicBaseline
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_alphaTab_alphaSkia_AlphaSkiaTextMetrics_getIdeographicBaseline
  (JNIEnv *, jobject);

/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaTextMetrics
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_AlphaSkiaTextMetrics_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
