/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alphaTab_alphaSkia_AlphaSkiaTextStyle */

#ifndef _Included_alphaTab_alphaSkia_AlphaSkiaTextStyle
#define _Included_alphaTab_alphaSkia_AlphaSkiaTextStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaTextStyle
 * Method:    alphaskiaTextStyleNew
 * Signature: ([Ljava/lang/String;IZ)J
 */
JNIEXPORT jlong JNICALL Java_alphaTab_alphaSkia_AlphaSkiaTextStyle_alphaskiaTextStyleNew
  (JNIEnv *, jclass, jobjectArray, jint, jboolean);

/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaTextStyle
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_AlphaSkiaTextStyle_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
