/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alphaTab_alphaSkia_AlphaSkiaPlatform */

#ifndef _Included_alphaTab_alphaSkia_AlphaSkiaPlatform
#define _Included_alphaTab_alphaSkia_AlphaSkiaPlatform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaPlatform
 * Method:    setTracingEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_AlphaSkiaPlatform_setTracingEnabled
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
