/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_alphatab_alphaskia_AlphaSkiaCanvas */

#ifndef _Included_net_alphatab_alphaskia_AlphaSkiaCanvas
#define _Included_net_alphatab_alphaskia_AlphaSkiaCanvas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    getColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_getColor
  (JNIEnv *, jobject);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    setColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_setColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    getLineWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_getLineWidth
  (JNIEnv *, jobject);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    setLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_setLineWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_close
  (JNIEnv *, jobject);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    beginRender
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_beginRender
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    drawImage
 * Signature: (Lnet/alphatab/alphaskia/AlphaSkiaImage;FF)V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_drawImage
  (JNIEnv *, jobject, jobject, jfloat, jfloat);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    endRender
 * Signature: ()Lnet/alphatab/alphaskia/AlphaSkiaImage;
 */
JNIEXPORT jobject JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_endRender
  (JNIEnv *, jobject);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    fillRect
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_fillRect
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    strokeRect
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_strokeRect
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    beginPath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_beginPath
  (JNIEnv *, jobject);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    closePath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_closePath
  (JNIEnv *, jobject);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    moveTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_moveTo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    lineTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_lineTo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    quadraticCurveTo
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_quadraticCurveTo
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    bezierCurveTo
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_bezierCurveTo
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    fillCircle
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_fillCircle
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    strokeCircle
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_strokeCircle
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    fill
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_fill
  (JNIEnv *, jobject);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    stroke
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_stroke
  (JNIEnv *, jobject);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    fillText
 * Signature: (Ljava/lang/String;Lnet/alphatab/alphaskia/AlphaSkiaTypeface;FFFLnet/alphatab/alphaskia/AlphaSkiaTextAlign;Lnet/alphatab/alphaskia/AlphaSkiaTextBaseline;)V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_fillText
  (JNIEnv *, jobject, jstring, jobject, jfloat, jfloat, jfloat, jobject, jobject);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    measureText
 * Signature: (Ljava/lang/String;Lnet/alphatab/alphaskia/AlphaSkiaTypeface;F)F
 */
JNIEXPORT jfloat JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_measureText
  (JNIEnv *, jobject, jstring, jobject, jfloat);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    beginRotate
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_beginRotate
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    endRotate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_endRotate
  (JNIEnv *, jobject);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    alphaskiaCanvasAllocate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_alphaskiaCanvasAllocate
  (JNIEnv *, jclass);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaCanvas
 * Method:    alphaskiaColorType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_alphatab_alphaskia_AlphaSkiaCanvas_alphaskiaColorType
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
