/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_alphatab_alphaskia_AlphaSkiaTypeface */

#ifndef _Included_net_alphatab_alphaskia_AlphaSkiaTypeface
#define _Included_net_alphatab_alphaskia_AlphaSkiaTypeface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaTypeface
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_alphatab_alphaskia_AlphaSkiaTypeface_release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaTypeface
 * Method:    register
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_alphatab_alphaskia_AlphaSkiaTypeface_register
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_alphatab_alphaskia_AlphaSkiaTypeface
 * Method:    makeFromName
 * Signature: (Ljava/lang/String;ZZ)J
 */
JNIEXPORT jlong JNICALL Java_net_alphatab_alphaskia_AlphaSkiaTypeface_makeFromName
  (JNIEnv *, jclass, jstring, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
