// <auto-generated>
// This file has been auto generated by a unit test in alphaTab.
// </auto-generated>
namespace AlphaSkia.Test;

public class AlphaTabGeneratedRenderTest : MusicSheetRenderTest
{
    protected override int[,] PartPositions => new int[,] {
        { 0, 0 },
        { 0, 164 },
        { 0, 202 },
        { 0, 208 },
        { 587, 455 }    };
    protected override int TotalWidth => 1300;
    protected override int TotalHeight => 519;
    protected override Func<AlphaSkiaCanvas, AlphaSkiaImage>[] AllParts => new [] { DrawMusicSheetPart1, DrawMusicSheetPart2, DrawMusicSheetPart3, DrawMusicSheetPart4, DrawMusicSheetPart5 };

    
    private AlphaSkiaImage DrawMusicSheetPart1(AlphaSkiaCanvas canvas)
    {
        canvas.BeginRender((int)1300, (int)164);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        TextAlign = AlphaSkiaTextAlign.Center;
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        TypeFace = GetTypeFace("PT Serif", false, false);
        FontSize = (float)32;
        TextAlign = AlphaSkiaTextAlign.Center;
        canvas.FillText("Title", TypeFace, FontSize, (float)650, (float)40, TextAlign, TextBaseline);
        TextAlign = AlphaSkiaTextAlign.Center;
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        TypeFace = GetTypeFace("PT Serif", false, false);
        FontSize = (float)20;
        TextAlign = AlphaSkiaTextAlign.Center;
        canvas.FillText("Subtitle", TypeFace, FontSize, (float)650, (float)72, TextAlign, TextBaseline);
        TextAlign = AlphaSkiaTextAlign.Center;
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        TypeFace = GetTypeFace("PT Serif", false, false);
        FontSize = (float)20;
        TextAlign = AlphaSkiaTextAlign.Center;
        canvas.FillText("Artist", TypeFace, FontSize, (float)650, (float)92, TextAlign, TextBaseline);
        TextAlign = AlphaSkiaTextAlign.Center;
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        TypeFace = GetTypeFace("PT Serif", false, false);
        FontSize = (float)20;
        TextAlign = AlphaSkiaTextAlign.Center;
        canvas.FillText("Album", TypeFace, FontSize, (float)650, (float)112, TextAlign, TextBaseline);
        TextAlign = AlphaSkiaTextAlign.Center;
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        TypeFace = GetTypeFace("PT Serif", false, false);
        FontSize = (float)15;
        TextAlign = AlphaSkiaTextAlign.Right;
        canvas.FillText("Music by Music Writer", TypeFace, FontSize, (float)1260, (float)132, TextAlign, TextBaseline);
        TextAlign = AlphaSkiaTextAlign.Center;
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        TypeFace = GetTypeFace("PT Serif", false, false);
        FontSize = (float)15;
        TextAlign = AlphaSkiaTextAlign.Left;
        canvas.FillText("Words by Words Writer", TypeFace, FontSize, (float)40, (float)132, TextAlign, TextBaseline);
        TextAlign = AlphaSkiaTextAlign.Center;
            return canvas.EndRender()!;
    }
    
    private AlphaSkiaImage DrawMusicSheetPart2(AlphaSkiaCanvas canvas)
    {
        canvas.BeginRender((int)1300, (int)38);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        TextAlign = AlphaSkiaTextAlign.Center;
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        TypeFace = GetTypeFace("PT Serif", false, true);
        FontSize = (float)12;
        TextAlign = AlphaSkiaTextAlign.Left;
        canvas.FillText("Guitar Standard Tuning", TypeFace, FontSize, (float)40, (float)3, TextAlign, TextBaseline);
        TextAlign = AlphaSkiaTextAlign.Center;
            return canvas.EndRender()!;
    }
    
    private AlphaSkiaImage DrawMusicSheetPart3(AlphaSkiaCanvas canvas)
    {
        canvas.BeginRender((int)1300, (int)6);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        TextAlign = AlphaSkiaTextAlign.Center;
            return canvas.EndRender()!;
    }
    
    private AlphaSkiaImage DrawMusicSheetPart4(AlphaSkiaCanvas canvas)
    {
        canvas.BeginRender((int)1300, (int)247);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        TextAlign = AlphaSkiaTextAlign.Left;
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        TypeFace = GetTypeFace("PT Serif", true, false);
        FontSize = (float)14;
        canvas.FillText("\xe1d5", MusicTypeface, (float)(MusicFontSize * 0.75), (float)167, (float)40, AlphaSkiaTextAlign.Left, AlphaSkiaTextBaseline.Alphabetic);
        canvas.FillText("= 120", TypeFace, FontSize, (float)179.5, (float)27, TextAlign, TextBaseline);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)165, (byte)165, (byte)165, (byte)255);
        canvas.FillRect((float)102, (float)79, (float)116, (float)1.04);
        canvas.FillRect((float)102, (float)88, (float)116, (float)1.04);
        canvas.FillRect((float)102, (float)97, (float)116, (float)1.04);
        canvas.FillRect((float)102, (float)106, (float)116, (float)1.04);
        canvas.FillRect((float)102, (float)115, (float)116, (float)1.04);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.FillText("\xe050", MusicTypeface, (float)(MusicFontSize * 1), (float)104, (float)106.52000000000001, AlphaSkiaTextAlign.Left, AlphaSkiaTextBaseline.Alphabetic);
        canvas.FillText("\xe084", MusicTypeface, (float)(MusicFontSize * 1), (float)137, (float)88, AlphaSkiaTextAlign.Left, AlphaSkiaTextBaseline.Alphabetic);
        canvas.FillText("\xe084", MusicTypeface, (float)(MusicFontSize * 1), (float)137, (float)106, AlphaSkiaTextAlign.Left, AlphaSkiaTextBaseline.Alphabetic);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)200, (byte)0, (byte)0, (byte)255);
        TypeFace = GetTypeFace("Roboto", false, false);
        FontSize = (float)11;
        canvas.FillText("1", TypeFace, FontSize, (float)151, (float)67.75, TextAlign, TextBaseline);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.FillRect((float)210, (float)79.1, (float)1, (float)36.000000000000014);
        canvas.FillRect((float)214, (float)79.1, (float)4, (float)36.000000000000014);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)100);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)100);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)100);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)165, (byte)165, (byte)165, (byte)255);
        canvas.FillRect((float)102, (float)158, (float)116, (float)1.04);
        canvas.FillRect((float)102, (float)169, (float)116, (float)1.04);
        canvas.FillRect((float)102, (float)180, (float)116, (float)1.04);
        canvas.FillRect((float)102, (float)191, (float)116, (float)1.04);
        canvas.FillRect((float)102, (float)202, (float)116, (float)1.04);
        canvas.FillRect((float)102, (float)213, (float)116, (float)1.04);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.FillText("\xe06d", MusicTypeface, (float)(MusicFontSize * 0.9230769230769231), (float)107, (float)185.79999999999998, AlphaSkiaTextAlign.Left, AlphaSkiaTextBaseline.Alphabetic);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        canvas.FillRect((float)210, (float)158.29999999999998, (float)1, (float)55);
        canvas.FillRect((float)214, (float)158.29999999999998, (float)4, (float)55);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)34, (byte)34, (byte)17, (byte)255);
        canvas.BeginPath();
        canvas.MoveTo((float)102, (float)79.1);
        canvas.LineTo((float)102, (float)213.3);
        canvas.Stroke();
        TypeFace = GetTypeFace("PT Serif", false, true);
        FontSize = (float)12;
        canvas.FillText("Track 1", TypeFace, FontSize, (float)50, (float)79.1, TextAlign, TextBaseline);
        canvas.FillRect((float)96, (float)67.1, (float)3, (float)158.20000000000002);
        canvas.BeginPath();
        canvas.MoveTo((float)96, (float)67.1);
        canvas.BezierCurveTo((float)96, (float)67.1, (float)96, (float)67.1, (float)108, (float)64.1);
        canvas.BezierCurveTo((float)102, (float)70.1, (float)96, (float)70.1, (float)96, (float)70.1);
        canvas.ClosePath();
        canvas.Fill();
        canvas.BeginPath();
        canvas.MoveTo((float)96, (float)225.3);
        canvas.BezierCurveTo((float)96, (float)225.3, (float)102, (float)225.3, (float)108, (float)228.3);
        canvas.BezierCurveTo((float)102, (float)222.3, (float)96, (float)222.3, (float)96, (float)222.3);
        canvas.ClosePath();
        canvas.Fill();
            return canvas.EndRender()!;
    }
    
    private AlphaSkiaImage DrawMusicSheetPart5(AlphaSkiaCanvas canvas)
    {
        canvas.BeginRender((int)124, (int)24);
        canvas.Color = AlphaSkiaCanvas.RgbaToColor((byte)0, (byte)0, (byte)0, (byte)255);
        TypeFace = GetTypeFace("Roboto", true, false);
        FontSize = (float)12;
        TextAlign = AlphaSkiaTextAlign.Left;
        canvas.FillText("rendered by alphaTab", TypeFace, FontSize, (float)0, (float)12, TextAlign, TextBaseline);
            return canvas.EndRender()!;
    }
}