#include "../include/AlphaTabGeneratedTest.h"

alphaskia_image_t draw_music_sheet_part_1(alphaskia_canvas_t canvas) {
    alphaskia_canvas_begin_render(canvas, 1300, 164, static_cast<float>(render_scale));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(153), static_cast<uint8_t>(204), static_cast<uint8_t>(30), static_cast<uint8_t>(255)));
    text_align = alphaskia_text_align_center;
    typeface = alphaskia_get_typeface("PT Serif", false, false);
    font_size = static_cast<float>(32);
    text_align = alphaskia_text_align_center;
    alphaskia_canvas_fill_text(canvas, u"Title", 5, typeface, font_size, static_cast<float>(650), static_cast<float>(40), text_align, text_baseline);
    text_align = alphaskia_text_align_center;
    typeface = alphaskia_get_typeface("PT Serif", false, false);
    font_size = static_cast<float>(20);
    text_align = alphaskia_text_align_center;
    alphaskia_canvas_fill_text(canvas, u"Subtitle", 8, typeface, font_size, static_cast<float>(650), static_cast<float>(72), text_align, text_baseline);
    text_align = alphaskia_text_align_center;
    typeface = alphaskia_get_typeface("PT Serif", false, false);
    font_size = static_cast<float>(20);
    text_align = alphaskia_text_align_center;
    alphaskia_canvas_fill_text(canvas, u"Artist", 6, typeface, font_size, static_cast<float>(650), static_cast<float>(92), text_align, text_baseline);
    text_align = alphaskia_text_align_center;
    typeface = alphaskia_get_typeface("PT Serif", false, false);
    font_size = static_cast<float>(20);
    text_align = alphaskia_text_align_center;
    alphaskia_canvas_fill_text(canvas, u"Album", 5, typeface, font_size, static_cast<float>(650), static_cast<float>(112), text_align, text_baseline);
    text_align = alphaskia_text_align_center;
    typeface = alphaskia_get_typeface("PT Serif", false, false);
    font_size = static_cast<float>(15);
    text_align = alphaskia_text_align_right;
    alphaskia_canvas_fill_text(canvas, u"Music by Music", 14, typeface, font_size, static_cast<float>(1260), static_cast<float>(132), text_align, text_baseline);
    text_align = alphaskia_text_align_center;
    typeface = alphaskia_get_typeface("PT Serif", false, false);
    font_size = static_cast<float>(15);
    text_align = alphaskia_text_align_left;
    alphaskia_canvas_fill_text(canvas, u"Words by Words", 14, typeface, font_size, static_cast<float>(40), static_cast<float>(132), text_align, text_baseline);
    text_align = alphaskia_text_align_center;
    return alphaskia_canvas_end_render(canvas);
}
alphaskia_image_t draw_music_sheet_part_2(alphaskia_canvas_t canvas) {
    alphaskia_canvas_begin_render(canvas, 1300, 38, static_cast<float>(render_scale));
    text_align = alphaskia_text_align_center;
    typeface = alphaskia_get_typeface("PT Serif", false, true);
    font_size = static_cast<float>(12);
    text_align = alphaskia_text_align_left;
    alphaskia_canvas_fill_text(canvas, u"Guitar Standard Tuning", 22, typeface, font_size, static_cast<float>(40), static_cast<float>(3), text_align, text_baseline);
    text_align = alphaskia_text_align_center;
    return alphaskia_canvas_end_render(canvas);
}
alphaskia_image_t draw_music_sheet_part_3(alphaskia_canvas_t canvas) {
    alphaskia_canvas_begin_render(canvas, 1300, 6, static_cast<float>(render_scale));
    text_align = alphaskia_text_align_center;
    return alphaskia_canvas_end_render(canvas);
}
alphaskia_image_t draw_music_sheet_part_4(alphaskia_canvas_t canvas) {
    alphaskia_canvas_begin_render(canvas, 1300, 373, static_cast<float>(render_scale));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    text_align = alphaskia_text_align_left;
    typeface = alphaskia_get_typeface("PT Serif", true, false);
    font_size = static_cast<float>(14);
    alphaskia_canvas_fill_text(canvas, u"\uE1D5", 1, music_typeface, static_cast<float>(music_font_size * 0.75), static_cast<float>(156.6767578125), static_cast<float>(40), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"= 120", 5, typeface, font_size, static_cast<float>(169.1767578125), static_cast<float>(27), text_align, text_baseline);
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(255)));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(92), static_cast<float>(130), static_cast<float>(254), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(92), static_cast<float>(139), static_cast<float>(254), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(92), static_cast<float>(148), static_cast<float>(254), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(92), static_cast<float>(157), static_cast<float>(254), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(92), static_cast<float>(166), static_cast<float>(254), static_cast<float>(1.04));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    alphaskia_canvas_fill_text(canvas, u"\uE050", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(94), static_cast<float>(157.52), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE084", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(127), static_cast<float>(139), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE084", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(127), static_cast<float>(157), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(200), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"1", 1, typeface, font_size, static_cast<float>(141), static_cast<float>(118.75), text_align, text_baseline);
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(152.1767578125), static_cast<float>(148), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE272", 1, music_typeface, static_cast<float>(music_font_size * 0.75), static_cast<float>(172.86069962449085), static_cast<float>(148), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 0.75), static_cast<float>(180.86069962449085), static_cast<float>(149), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(156.6767578125), static_cast<float>(144));
    alphaskia_canvas_line_to(canvas, static_cast<float>(170.855110706305), static_cast<float>(133.50723450810483));
    alphaskia_canvas_line_to(canvas, static_cast<float>(184.23569962449085), static_cast<float>(145));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(192.23569962449085), static_cast<float>(148), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 0.75), static_cast<float>(220.91964143648167), static_cast<float>(144.5), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(196.73569962449085), static_cast<float>(144));
    alphaskia_canvas_line_to(canvas, static_cast<float>(209.12929655256082), static_cast<float>(131.33765133817155));
    alphaskia_canvas_line_to(canvas, static_cast<float>(224.29464143648167), static_cast<float>(140.5));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(232.29464143648167), static_cast<float>(148), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE262", 1, music_typeface, static_cast<float>(music_font_size * 0.75), static_cast<float>(252.9785832484725), static_cast<float>(143.5), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 0.75), static_cast<float>(260.9785832484725), static_cast<float>(144.5), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(236.79464143648167), static_cast<float>(144));
    alphaskia_canvas_line_to(canvas, static_cast<float>(249.1882383645516), static_cast<float>(131.33765133817155));
    alphaskia_canvas_line_to(canvas, static_cast<float>(264.3535832484725), static_cast<float>(140.5));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(272.3535832484725), static_cast<float>(148), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 0.75), static_cast<float>(294.5517916242362), static_cast<float>(140), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(276.8535832484725), static_cast<float>(152));
    alphaskia_canvas_line_to(canvas, static_cast<float>(292.1060513036615), static_cast<float>(156.93783819474976));
    alphaskia_canvas_line_to(canvas, static_cast<float>(297.9267916242362), static_cast<float>(142));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(305.9267916242362), static_cast<float>(148), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE262", 1, music_typeface, static_cast<float>(music_font_size * 0.75), static_cast<float>(324.625), static_cast<float>(139), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 0.75), static_cast<float>(332.625), static_cast<float>(140), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(310.4267916242362), static_cast<float>(152));
    alphaskia_canvas_line_to(canvas, static_cast<float>(327.2193887931866), static_cast<float>(157.24460932567123));
    alphaskia_canvas_line_to(canvas, static_cast<float>(336), static_cast<float>(142));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(345), static_cast<float>(130.1), static_cast<float>(1), static_cast<float>(36));
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(0.96));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(152.1767578125), static_cast<float>(148));
    alphaskia_canvas_line_to(canvas, static_cast<float>(152.1767578125), static_cast<float>(175));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(1));
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(0.96));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(192.23569962449085), static_cast<float>(148));
    alphaskia_canvas_line_to(canvas, static_cast<float>(192.23569962449085), static_cast<float>(175));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(1));
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(0.96));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(232.29464143648167), static_cast<float>(148));
    alphaskia_canvas_line_to(canvas, static_cast<float>(232.29464143648167), static_cast<float>(175));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(1));
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(0.96));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(281.3535832484725), static_cast<float>(148));
    alphaskia_canvas_line_to(canvas, static_cast<float>(281.3535832484725), static_cast<float>(121));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(1));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(281.3535832484725), static_cast<float>(121));
    alphaskia_canvas_line_to(canvas, static_cast<float>(314.9267916242362), static_cast<float>(121));
    alphaskia_canvas_line_to(canvas, static_cast<float>(314.9267916242362), static_cast<float>(125));
    alphaskia_canvas_line_to(canvas, static_cast<float>(281.3535832484725), static_cast<float>(125));
    alphaskia_canvas_close_path(canvas);
    alphaskia_canvas_fill(canvas);
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(0.96));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(314.9267916242362), static_cast<float>(148));
    alphaskia_canvas_line_to(canvas, static_cast<float>(314.9267916242362), static_cast<float>(121));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(1));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(100)));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(255)));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(346), static_cast<float>(130), static_cast<float>(126), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(346), static_cast<float>(139), static_cast<float>(126), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(346), static_cast<float>(148), static_cast<float>(126), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(346), static_cast<float>(157), static_cast<float>(126), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(346), static_cast<float>(166), static_cast<float>(126), static_cast<float>(1.04));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(200), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"2", 1, typeface, font_size, static_cast<float>(346), static_cast<float>(118.75), text_align, text_baseline);
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(357.1767578125), static_cast<float>(139), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(378.359547484596), static_cast<float>(139), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(399.542337156692), static_cast<float>(161.5), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A3", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(426.623147703567), static_cast<float>(157), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(471), static_cast<float>(130.1), static_cast<float>(1), static_cast<float>(36));
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(0.96));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(366.1767578125), static_cast<float>(139));
    alphaskia_canvas_line_to(canvas, static_cast<float>(366.1767578125), static_cast<float>(112));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(1));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(366.1767578125), static_cast<float>(112));
    alphaskia_canvas_line_to(canvas, static_cast<float>(387.359547484596), static_cast<float>(117));
    alphaskia_canvas_line_to(canvas, static_cast<float>(387.359547484596), static_cast<float>(121));
    alphaskia_canvas_line_to(canvas, static_cast<float>(366.1767578125), static_cast<float>(116));
    alphaskia_canvas_close_path(canvas);
    alphaskia_canvas_fill(canvas);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(366.1767578125), static_cast<float>(118));
    alphaskia_canvas_line_to(canvas, static_cast<float>(387.359547484596), static_cast<float>(123));
    alphaskia_canvas_line_to(canvas, static_cast<float>(387.359547484596), static_cast<float>(127));
    alphaskia_canvas_line_to(canvas, static_cast<float>(366.1767578125), static_cast<float>(122));
    alphaskia_canvas_close_path(canvas);
    alphaskia_canvas_fill(canvas);
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(0.96));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(387.359547484596), static_cast<float>(139));
    alphaskia_canvas_line_to(canvas, static_cast<float>(387.359547484596), static_cast<float>(117));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(1));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(387.359547484596), static_cast<float>(117));
    alphaskia_canvas_line_to(canvas, static_cast<float>(408.542337156692), static_cast<float>(122));
    alphaskia_canvas_line_to(canvas, static_cast<float>(408.542337156692), static_cast<float>(126));
    alphaskia_canvas_line_to(canvas, static_cast<float>(387.359547484596), static_cast<float>(121));
    alphaskia_canvas_close_path(canvas);
    alphaskia_canvas_fill(canvas);
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(0.96));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(408.542337156692), static_cast<float>(161.5));
    alphaskia_canvas_line_to(canvas, static_cast<float>(408.542337156692), static_cast<float>(122));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(1));
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(0.96));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(435.623147703567), static_cast<float>(130));
    alphaskia_canvas_line_to(canvas, static_cast<float>(435.623147703567), static_cast<float>(157));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(1));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(100)));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    text_align = alphaskia_text_align_center;
    text_baseline = alphaskia_text_baseline_middle;
    typeface = alphaskia_get_typeface("PT Serif", false, true);
    font_size = static_cast<float>(12);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(366.1767578125), static_cast<float>(102));
    alphaskia_canvas_line_to(canvas, static_cast<float>(366.1767578125), static_cast<float>(97));
    alphaskia_canvas_line_to(canvas, static_cast<float>(394.7559555656507), static_cast<float>(104));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(407.04394995041633), static_cast<float>(107));
    alphaskia_canvas_line_to(canvas, static_cast<float>(435.623147703567), static_cast<float>(115));
    alphaskia_canvas_line_to(canvas, static_cast<float>(435.623147703567), static_cast<float>(120));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_fill_text(canvas, u"3", 1, typeface, font_size, static_cast<float>(400.8999527580335), static_cast<float>(106), text_align, text_baseline);
    text_align = alphaskia_text_align_left;
    text_baseline = alphaskia_text_baseline_top;
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(255)));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(472), static_cast<float>(130), static_cast<float>(206), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(472), static_cast<float>(139), static_cast<float>(206), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(472), static_cast<float>(148), static_cast<float>(206), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(472), static_cast<float>(157), static_cast<float>(206), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(472), static_cast<float>(166), static_cast<float>(206), static_cast<float>(1.04));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(200), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"3", 1, typeface, font_size, static_cast<float>(472), static_cast<float>(118.75), text_align, text_baseline);
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(496.32666015625), static_cast<float>(157), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(496.32666015625), static_cast<float>(143.5), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(496.32666015625), static_cast<float>(134.5), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_begin_rotate(canvas, static_cast<float>(527.8699951171875), static_cast<float>(172), static_cast<float>(-90));
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(0), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(10.799999999999999), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(21.599999999999998), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(32.4), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_end_rotate(canvas);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(527.8699951171875), static_cast<float>(180));
    alphaskia_canvas_line_to(canvas, static_cast<float>(531.8699951171875), static_cast<float>(172));
    alphaskia_canvas_line_to(canvas, static_cast<float>(523.8699951171875), static_cast<float>(172));
    alphaskia_canvas_close_path(canvas);
    alphaskia_canvas_fill(canvas);
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(255)));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(533.8699951171875), static_cast<float>(175), static_cast<float>(15), static_cast<float>(1));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(536.8699951171875), static_cast<float>(175), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(536.8699951171875), static_cast<float>(166), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(536.8699951171875), static_cast<float>(157), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(536.8699951171875), static_cast<float>(143.5), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(536.8699951171875), static_cast<float>(134.5), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(255)));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(574.413330078125), static_cast<float>(175), static_cast<float>(15), static_cast<float>(1));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(574.413330078125), static_cast<float>(184), static_cast<float>(15), static_cast<float>(1));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(577.413330078125), static_cast<float>(184), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(577.413330078125), static_cast<float>(166), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(577.413330078125), static_cast<float>(152.5), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_begin_rotate(canvas, static_cast<float>(596.9566650390625), static_cast<float>(137.5), static_cast<float>(90));
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(0), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(10.799999999999999), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(21.599999999999998), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(32.4), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(43.199999999999996), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_end_rotate(canvas);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(596.9566650390625), static_cast<float>(129.5));
    alphaskia_canvas_line_to(canvas, static_cast<float>(600.9566650390625), static_cast<float>(137.5));
    alphaskia_canvas_line_to(canvas, static_cast<float>(592.9566650390625), static_cast<float>(137.5));
    alphaskia_canvas_close_path(canvas);
    alphaskia_canvas_fill(canvas);
    alphaskia_canvas_fill_text(canvas, u"\uE262", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(607.9566650390625), static_cast<float>(143.5), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(255)));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(614.9566650390625), static_cast<float>(175), static_cast<float>(15), static_cast<float>(1));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(614.9566650390625), static_cast<float>(184), static_cast<float>(15), static_cast<float>(1));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(617.9566650390625), static_cast<float>(184), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(617.9566650390625), static_cast<float>(166), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(617.9566650390625), static_cast<float>(152.5), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(617.9566650390625), static_cast<float>(143.5), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uE0A4", 1, music_typeface, static_cast<float>(music_font_size * 1), static_cast<float>(617.9566650390625), static_cast<float>(134.5), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(670), static_cast<float>(130.1), static_cast<float>(1), static_cast<float>(36));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(674), static_cast<float>(130.1), static_cast<float>(4), static_cast<float>(36));
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(0.96));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(496.32666015625), static_cast<float>(134.5));
    alphaskia_canvas_line_to(canvas, static_cast<float>(496.32666015625), static_cast<float>(184));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(1));
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(0.96));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(545.8699951171875), static_cast<float>(107.5));
    alphaskia_canvas_line_to(canvas, static_cast<float>(545.8699951171875), static_cast<float>(175));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(1));
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(0.96));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(586.413330078125), static_cast<float>(125.5));
    alphaskia_canvas_line_to(canvas, static_cast<float>(586.413330078125), static_cast<float>(184));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(1));
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(0.96));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(626.9566650390625), static_cast<float>(107.5));
    alphaskia_canvas_line_to(canvas, static_cast<float>(626.9566650390625), static_cast<float>(184));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_set_line_width(canvas, static_cast<float>(1));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(100)));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(255)));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(92), static_cast<float>(284), static_cast<float>(254), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(92), static_cast<float>(295), static_cast<float>(254), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(92), static_cast<float>(306), static_cast<float>(254), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(92), static_cast<float>(317), static_cast<float>(61.02685546875), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(161.32666015625), static_cast<float>(317), static_cast<float>(31.759140014648438), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(201.38560485839844), static_cast<float>(317), static_cast<float>(31.759140014648438), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(241.44454956054688), static_cast<float>(317), static_cast<float>(31.759124755859375), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(281.50347900390625), static_cast<float>(317), static_cast<float>(25.273406982421875), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(315.0766906738281), static_cast<float>(317), static_cast<float>(30.923309326171875), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(92), static_cast<float>(328), static_cast<float>(254), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(92), static_cast<float>(339), static_cast<float>(254), static_cast<float>(1.04));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    alphaskia_canvas_fill_text(canvas, u"\uE06D", 1, music_typeface, static_cast<float>(music_font_size * 0.9230769230769231), static_cast<float>(97), static_cast<float>(311.8), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    text_baseline = alphaskia_text_baseline_middle;
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(163.32666015625), static_cast<float>(317.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"9", 1, typeface, font_size, static_cast<float>(153.02685546875), static_cast<float>(317.3), text_align, text_baseline);
    text_baseline = alphaskia_text_baseline_top;
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(188.23569962449085), static_cast<float>(274.7));
    alphaskia_canvas_line_to(canvas, static_cast<float>(185.23569962449085), static_cast<float>(280.7));
    alphaskia_canvas_line_to(canvas, static_cast<float>(191.23569962449085), static_cast<float>(280.7));
    alphaskia_canvas_close_path(canvas);
    alphaskia_canvas_fill(canvas);
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(162.32666015625), static_cast<float>(317.3));
    alphaskia_canvas_bezier_curve_to(canvas, static_cast<float>(175.28117989037042), static_cast<float>(317.3), static_cast<float>(188.23569962449085), static_cast<float>(317.3), static_cast<float>(188.23569962449085), static_cast<float>(280.7));
    alphaskia_canvas_stroke(canvas);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"\u00BC", 1, typeface, font_size, static_cast<float>(183.47495743699085), static_cast<float>(260.7), text_align, text_baseline);
    text_baseline = alphaskia_text_baseline_middle;
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(203.38560196824085), static_cast<float>(317.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"9", 1, typeface, font_size, static_cast<float>(193.08579728074085), static_cast<float>(317.3), text_align, text_baseline);
    text_baseline = alphaskia_text_baseline_top;
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(228.29464143648167), static_cast<float>(268.7));
    alphaskia_canvas_line_to(canvas, static_cast<float>(225.29464143648167), static_cast<float>(274.7));
    alphaskia_canvas_line_to(canvas, static_cast<float>(231.29464143648167), static_cast<float>(274.7));
    alphaskia_canvas_close_path(canvas);
    alphaskia_canvas_fill(canvas);
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(202.38560196824085), static_cast<float>(317.3));
    alphaskia_canvas_bezier_curve_to(canvas, static_cast<float>(215.34012170236127), static_cast<float>(317.3), static_cast<float>(228.29464143648167), static_cast<float>(317.3), static_cast<float>(228.29464143648167), static_cast<float>(274.7));
    alphaskia_canvas_stroke(canvas);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"\u00BD", 1, typeface, font_size, static_cast<float>(223.25142854585667), static_cast<float>(254.7), text_align, text_baseline);
    text_baseline = alphaskia_text_baseline_middle;
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(243.44454378023167), static_cast<float>(317.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"9", 1, typeface, font_size, static_cast<float>(233.14473909273167), static_cast<float>(317.3), text_align, text_baseline);
    text_baseline = alphaskia_text_baseline_top;
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(268.3535832484725), static_cast<float>(256.7));
    alphaskia_canvas_line_to(canvas, static_cast<float>(265.3535832484725), static_cast<float>(262.7));
    alphaskia_canvas_line_to(canvas, static_cast<float>(271.3535832484725), static_cast<float>(262.7));
    alphaskia_canvas_close_path(canvas);
    alphaskia_canvas_fill(canvas);
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(242.44454378023167), static_cast<float>(317.3));
    alphaskia_canvas_bezier_curve_to(canvas, static_cast<float>(255.39906351435206), static_cast<float>(317.3), static_cast<float>(268.3535832484725), static_cast<float>(317.3), static_cast<float>(268.3535832484725), static_cast<float>(262.7));
    alphaskia_canvas_stroke(canvas);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"full", 4, typeface, font_size, static_cast<float>(259.3589543422225), static_cast<float>(242.7), text_align, text_baseline);
    text_baseline = alphaskia_text_baseline_middle;
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(283.5034855922225), static_cast<float>(317.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"9", 1, typeface, font_size, static_cast<float>(273.2036809047225), static_cast<float>(317.3), text_align, text_baseline);
    text_baseline = alphaskia_text_baseline_top;
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(301.9267916242362), static_cast<float>(244.7));
    alphaskia_canvas_line_to(canvas, static_cast<float>(298.9267916242362), static_cast<float>(250.7));
    alphaskia_canvas_line_to(canvas, static_cast<float>(304.9267916242362), static_cast<float>(250.7));
    alphaskia_canvas_close_path(canvas);
    alphaskia_canvas_fill(canvas);
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(282.5034855922225), static_cast<float>(317.3));
    alphaskia_canvas_bezier_curve_to(canvas, static_cast<float>(292.2151386082294), static_cast<float>(317.3), static_cast<float>(301.9267916242362), static_cast<float>(317.3), static_cast<float>(301.9267916242362), static_cast<float>(250.7));
    alphaskia_canvas_stroke(canvas);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"1\u00BD", 2, typeface, font_size, static_cast<float>(293.2336763898612), static_cast<float>(230.7), text_align, text_baseline);
    text_baseline = alphaskia_text_baseline_middle;
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(317.0766939679862), static_cast<float>(317.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"9", 1, typeface, font_size, static_cast<float>(306.7768892804862), static_cast<float>(317.3), text_align, text_baseline);
    text_baseline = alphaskia_text_baseline_top;
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(340), static_cast<float>(232.7));
    alphaskia_canvas_line_to(canvas, static_cast<float>(337), static_cast<float>(238.7));
    alphaskia_canvas_line_to(canvas, static_cast<float>(343), static_cast<float>(238.7));
    alphaskia_canvas_close_path(canvas);
    alphaskia_canvas_fill(canvas);
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(316.0766939679862), static_cast<float>(317.3));
    alphaskia_canvas_bezier_curve_to(canvas, static_cast<float>(328.0383469839931), static_cast<float>(317.3), static_cast<float>(340), static_cast<float>(317.3), static_cast<float>(340), static_cast<float>(238.7));
    alphaskia_canvas_stroke(canvas);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"2", 1, typeface, font_size, static_cast<float>(336.35009765625), static_cast<float>(218.7), text_align, text_baseline);
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(345), static_cast<float>(284.3), static_cast<float>(1), static_cast<float>(54.99999999999994));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(255)));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(346), static_cast<float>(284), static_cast<float>(126), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(346), static_cast<float>(295), static_cast<float>(12.02685546875), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(366.32666015625), static_cast<float>(295), static_cast<float>(12.882984161376953), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(387.50944900512695), static_cast<float>(295), static_cast<float>(84.49055099487305), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(346), static_cast<float>(306), static_cast<float>(126), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(346), static_cast<float>(317), static_cast<float>(54.392433166503906), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(408.6922378540039), static_cast<float>(317), static_cast<float>(18.781005859375), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(435.7730484008789), static_cast<float>(317), static_cast<float>(36.226951599121094), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(346), static_cast<float>(328), static_cast<float>(126), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(346), static_cast<float>(339), static_cast<float>(126), static_cast<float>(1.04));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    text_baseline = alphaskia_text_baseline_middle;
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(368.32666015625), static_cast<float>(295.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"3", 1, typeface, font_size, static_cast<float>(358.02685546875), static_cast<float>(295.3), text_align, text_baseline);
    text_baseline = alphaskia_text_baseline_top;
    text_baseline = alphaskia_text_baseline_middle;
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(389.509449828346), static_cast<float>(295.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"3", 1, typeface, font_size, static_cast<float>(379.209645140846), static_cast<float>(295.3), text_align, text_baseline);
    text_baseline = alphaskia_text_baseline_top;
    text_baseline = alphaskia_text_baseline_middle;
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(410.692239500442), static_cast<float>(317.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"3", 1, typeface, font_size, static_cast<float>(400.392434812942), static_cast<float>(317.3), text_align, text_baseline);
    text_baseline = alphaskia_text_baseline_top;
    text_baseline = alphaskia_text_baseline_middle;
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(437.773050047317), static_cast<float>(317.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"5", 1, typeface, font_size, static_cast<float>(427.473245359817), static_cast<float>(317.3), text_align, text_baseline);
    text_baseline = alphaskia_text_baseline_top;
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(471), static_cast<float>(284.3), static_cast<float>(1), static_cast<float>(54.99999999999994));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(165), static_cast<uint8_t>(255)));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(472), static_cast<float>(284), static_cast<float>(25.1767578125), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(505.4765625), static_cast<float>(284), static_cast<float>(32.2435302734375), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(546.0198974609375), static_cast<float>(284), static_cast<float>(72.786865234375), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(627.1065673828125), static_cast<float>(284), static_cast<float>(50.8934326171875), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(472), static_cast<float>(295), static_cast<float>(25.1767578125), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(505.4765625), static_cast<float>(295), static_cast<float>(32.2435302734375), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(546.0198974609375), static_cast<float>(295), static_cast<float>(72.786865234375), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(627.1065673828125), static_cast<float>(295), static_cast<float>(50.8934326171875), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(472), static_cast<float>(306), static_cast<float>(25.1767578125), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(505.4765625), static_cast<float>(306), static_cast<float>(32.2435302734375), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(546.0198974609375), static_cast<float>(306), static_cast<float>(32.2435302734375), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(586.563232421875), static_cast<float>(306), static_cast<float>(32.2435302734375), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(627.1065673828125), static_cast<float>(306), static_cast<float>(50.8934326171875), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(472), static_cast<float>(317), static_cast<float>(65.7200927734375), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(546.0198974609375), static_cast<float>(317), static_cast<float>(32.2435302734375), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(586.563232421875), static_cast<float>(317), static_cast<float>(32.2435302734375), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(627.1065673828125), static_cast<float>(317), static_cast<float>(50.8934326171875), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(472), static_cast<float>(328), static_cast<float>(65.7200927734375), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(546.0198974609375), static_cast<float>(328), static_cast<float>(32.2435302734375), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(586.563232421875), static_cast<float>(328), static_cast<float>(32.2435302734375), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(627.1065673828125), static_cast<float>(328), static_cast<float>(50.8934326171875), static_cast<float>(1.04));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(472), static_cast<float>(339), static_cast<float>(206), static_cast<float>(1.04));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(488), static_cast<float>(275.8));
    alphaskia_canvas_line_to(canvas, static_cast<float>(488), static_cast<float>(312.8));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(488), static_cast<float>(275.8));
    alphaskia_canvas_line_to(canvas, static_cast<float>(492), static_cast<float>(283.8));
    alphaskia_canvas_line_to(canvas, static_cast<float>(484), static_cast<float>(283.8));
    alphaskia_canvas_close_path(canvas);
    alphaskia_canvas_fill(canvas);
    text_baseline = alphaskia_text_baseline_middle;
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(507.4765625), static_cast<float>(284.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"0", 1, typeface, font_size, static_cast<float>(497.1767578125), static_cast<float>(284.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(507.4765625), static_cast<float>(295.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"1", 1, typeface, font_size, static_cast<float>(497.1767578125), static_cast<float>(295.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(507.4765625), static_cast<float>(306.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"0", 1, typeface, font_size, static_cast<float>(497.1767578125), static_cast<float>(306.3), text_align, text_baseline);
    text_baseline = alphaskia_text_baseline_top;
    alphaskia_canvas_begin_rotate(canvas, static_cast<float>(527.7200927734375), static_cast<float>(326.8), static_cast<float>(-90));
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(0), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(10.799999999999999), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(21.599999999999998), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(32.4), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(43.199999999999996), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_end_rotate(canvas);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(528), static_cast<float>(334.8));
    alphaskia_canvas_line_to(canvas, static_cast<float>(532), static_cast<float>(326.8));
    alphaskia_canvas_line_to(canvas, static_cast<float>(524), static_cast<float>(326.8));
    alphaskia_canvas_close_path(canvas);
    alphaskia_canvas_fill(canvas);
    text_baseline = alphaskia_text_baseline_middle;
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(548.0198974609375), static_cast<float>(284.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"0", 1, typeface, font_size, static_cast<float>(537.7200927734375), static_cast<float>(284.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(548.0198974609375), static_cast<float>(295.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"1", 1, typeface, font_size, static_cast<float>(537.7200927734375), static_cast<float>(295.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(548.0198974609375), static_cast<float>(306.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"0", 1, typeface, font_size, static_cast<float>(537.7200927734375), static_cast<float>(306.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(548.0198974609375), static_cast<float>(317.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"2", 1, typeface, font_size, static_cast<float>(537.7200927734375), static_cast<float>(317.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(548.0198974609375), static_cast<float>(328.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"3", 1, typeface, font_size, static_cast<float>(537.7200927734375), static_cast<float>(328.3), text_align, text_baseline);
    text_baseline = alphaskia_text_baseline_top;
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(569), static_cast<float>(297.8));
    alphaskia_canvas_line_to(canvas, static_cast<float>(569), static_cast<float>(334.8));
    alphaskia_canvas_stroke(canvas);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(569), static_cast<float>(297.8));
    alphaskia_canvas_line_to(canvas, static_cast<float>(573), static_cast<float>(305.8));
    alphaskia_canvas_line_to(canvas, static_cast<float>(565), static_cast<float>(305.8));
    alphaskia_canvas_close_path(canvas);
    alphaskia_canvas_fill(canvas);
    text_baseline = alphaskia_text_baseline_middle;
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(588.563232421875), static_cast<float>(306.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"2", 1, typeface, font_size, static_cast<float>(578.263427734375), static_cast<float>(306.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(588.563232421875), static_cast<float>(317.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"2", 1, typeface, font_size, static_cast<float>(578.263427734375), static_cast<float>(317.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(588.563232421875), static_cast<float>(328.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"0", 1, typeface, font_size, static_cast<float>(578.263427734375), static_cast<float>(328.3), text_align, text_baseline);
    text_baseline = alphaskia_text_baseline_top;
    alphaskia_canvas_begin_rotate(canvas, static_cast<float>(596.8067626953125), static_cast<float>(283.8), static_cast<float>(90));
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(0), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(10.799999999999999), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(21.599999999999998), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(32.4), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_fill_text(canvas, u"\uEAA4", 1, music_typeface, static_cast<float>(music_font_size * 1.2), static_cast<float>(43.199999999999996), static_cast<float>(10.799999999999999), alphaskia_text_align_left, alphaskia_text_baseline_alphabetic);
    alphaskia_canvas_end_rotate(canvas);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(597), static_cast<float>(275.8));
    alphaskia_canvas_line_to(canvas, static_cast<float>(601), static_cast<float>(283.8));
    alphaskia_canvas_line_to(canvas, static_cast<float>(593), static_cast<float>(283.8));
    alphaskia_canvas_close_path(canvas);
    alphaskia_canvas_fill(canvas);
    text_baseline = alphaskia_text_baseline_middle;
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(629.1065673828125), static_cast<float>(284.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"0", 1, typeface, font_size, static_cast<float>(618.8067626953125), static_cast<float>(284.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(629.1065673828125), static_cast<float>(295.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"2", 1, typeface, font_size, static_cast<float>(618.8067626953125), static_cast<float>(295.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(629.1065673828125), static_cast<float>(306.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"2", 1, typeface, font_size, static_cast<float>(618.8067626953125), static_cast<float>(306.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(629.1065673828125), static_cast<float>(317.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"2", 1, typeface, font_size, static_cast<float>(618.8067626953125), static_cast<float>(317.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(11);
    alphaskia_canvas_fill_text(canvas, u"", 0, typeface, font_size, static_cast<float>(629.1065673828125), static_cast<float>(328.3), text_align, text_baseline);
    typeface = alphaskia_get_typeface("Roboto", false, false);
    font_size = static_cast<float>(13);
    alphaskia_canvas_fill_text(canvas, u"0", 1, typeface, font_size, static_cast<float>(618.8067626953125), static_cast<float>(328.3), text_align, text_baseline);
    text_baseline = alphaskia_text_baseline_top;
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(670), static_cast<float>(284.3), static_cast<float>(1), static_cast<float>(54.99999999999994));
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(674), static_cast<float>(284.3), static_cast<float>(4), static_cast<float>(54.99999999999994));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(153), static_cast<uint8_t>(51), static_cast<uint8_t>(204), static_cast<uint8_t>(100)));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(92), static_cast<float>(130.1));
    alphaskia_canvas_line_to(canvas, static_cast<float>(92), static_cast<float>(339.3));
    alphaskia_canvas_stroke(canvas);
    typeface = alphaskia_get_typeface("PT Serif", false, true);
    font_size = static_cast<float>(12);
    alphaskia_canvas_fill_text(canvas, u"s.guit.", 7, typeface, font_size, static_cast<float>(50), static_cast<float>(130.1), text_align, text_baseline);
    alphaskia_canvas_fill_rect(canvas, static_cast<float>(86), static_cast<float>(118.1), static_cast<float>(3), static_cast<float>(233.20000000000002));
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(86), static_cast<float>(118.1));
    alphaskia_canvas_bezier_curve_to(canvas, static_cast<float>(86), static_cast<float>(118.1), static_cast<float>(86), static_cast<float>(118.1), static_cast<float>(98), static_cast<float>(115.1));
    alphaskia_canvas_bezier_curve_to(canvas, static_cast<float>(92), static_cast<float>(121.1), static_cast<float>(86), static_cast<float>(121.1), static_cast<float>(86), static_cast<float>(121.1));
    alphaskia_canvas_close_path(canvas);
    alphaskia_canvas_fill(canvas);
    alphaskia_canvas_begin_path(canvas);
    alphaskia_canvas_move_to(canvas, static_cast<float>(86), static_cast<float>(351.3));
    alphaskia_canvas_bezier_curve_to(canvas, static_cast<float>(86), static_cast<float>(351.3), static_cast<float>(92), static_cast<float>(351.3), static_cast<float>(98), static_cast<float>(354.3));
    alphaskia_canvas_bezier_curve_to(canvas, static_cast<float>(92), static_cast<float>(348.3), static_cast<float>(86), static_cast<float>(348.3), static_cast<float>(86), static_cast<float>(348.3));
    alphaskia_canvas_close_path(canvas);
    alphaskia_canvas_fill(canvas);
    return alphaskia_canvas_end_render(canvas);
}
alphaskia_image_t draw_music_sheet_part_5(alphaskia_canvas_t canvas) {
    alphaskia_canvas_begin_render(canvas, 116, 24, static_cast<float>(render_scale));
    alphaskia_canvas_set_color(canvas, alphaskia_rgba_to_color(static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(0), static_cast<uint8_t>(255)));
    typeface = alphaskia_get_typeface("Roboto", true, false);
    font_size = static_cast<float>(12);
    text_align = alphaskia_text_align_left;
    alphaskia_canvas_fill_text(canvas, u"rendered by alphaTab", 20, typeface, font_size, static_cast<float>(0), static_cast<float>(12), text_align, text_baseline);
    return alphaskia_canvas_end_render(canvas);
}
std::array<std::array<float, 4>, 5> part_positions = 
{{
        {static_cast<float>(0), static_cast<float>(0), static_cast<float>(1300), static_cast<float>(164)}, {static_cast<float>(0), static_cast<float>(164), static_cast<float>(1300), static_cast<float>(38)}, {static_cast<float>(0), static_cast<float>(202), static_cast<float>(1300), static_cast<float>(6)}, {static_cast<float>(0), static_cast<float>(208), static_cast<float>(1300), static_cast<float>(373)}, {static_cast<float>(591.962890625), static_cast<float>(581), static_cast<float>(116.07421875), static_cast<float>(24)}
    }};
int32_t total_width  = 1300;
int32_t total_height  = 605;
std::array<render_function_t, 5> all_parts = 
{
    &draw_music_sheet_part_1, &draw_music_sheet_part_2, &draw_music_sheet_part_3, &draw_music_sheet_part_4, &draw_music_sheet_part_5
};
