/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alphaTab_alphaSkia_NativeMethods */

#ifndef _Included_alphaTab_alphaSkia_NativeMethods
#define _Included_alphaTab_alphaSkia_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaGetColorType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaGetColorType
        (JNIEnv *, jclass);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaDataNewCopy
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaDataNewCopy
        (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaDataGetData
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaDataGetData
        (JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaDataFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaDataFree
(JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaTypefaceRegister
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaTypefaceRegister
        (JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaTypefaceFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaTypefaceFree
(JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaTypefaceMakeFromName
 * Signature: (Ljava/lang/String;ZZ)J
 */
JNIEXPORT jlong JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaTypefaceMakeFromName
        (JNIEnv *, jclass, jstring, jboolean, jboolean);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaTypefaceGetFamilyName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaTypefaceGetFamilyName
        (JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaTypefaceIsBold
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaTypefaceIsBold
        (JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaTypefaceIsItalic
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaTypefaceIsItalic
        (JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaImageGetWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaImageGetWidth
        (JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaImageGetHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaImageGetHeight
        (JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaImageReadPixels
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaImageReadPixels
        (JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaImageEncodePng
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaImageEncodePng
        (JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaImageDecode
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaImageDecode
        (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaImageFromPixels
 * Signature: (II[B)J
 */
JNIEXPORT jlong JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaImageFromPixels
        (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaImageFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaImageFree
(JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasNew
        (JNIEnv *, jclass);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasFree
(JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasSetColor
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasSetColor
(JNIEnv *, jclass, jlong, jint);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasGetColor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasGetColor
        (JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasSetLineWidth
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasSetLineWidth
(JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasGetLineWidth
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasGetLineWidth
        (JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasBeginRender
 * Signature: (JIIF)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasBeginRender
(JNIEnv *, jclass, jlong, jint, jint, jfloat);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasEndRender
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasEndRender
        (JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasFillRect
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasFillRect
(JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasStrokeRect
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasStrokeRect
(JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasBeginPath
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasBeginPath
(JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasClosePath
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasClosePath
(JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasMoveTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasMoveTo
(JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasLineTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasLineTo
(JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasQuadraticCurveTo
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasQuadraticCurveTo
(JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasBezierCurveTo
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasBezierCurveTo
(JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasFillCircle
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasFillCircle
(JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasStrokeCircle
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasStrokeCircle
(JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasFill
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasFill
(JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasStroke
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasStroke
(JNIEnv *, jclass, jlong);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasDrawImage
 * Signature: (JJFFFF)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasDrawImage
(JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasFillText
 * Signature: (JLjava/lang/String;JFFFII)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasFillText
(JNIEnv *, jclass, jlong, jstring, jlong, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasMeasureText
 * Signature: (JLjava/lang/String;JF)F
 */
JNIEXPORT jfloat JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasMeasureText
        (JNIEnv *, jclass, jlong, jstring, jlong, jfloat);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasBeginRotate
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasBeginRotate
(JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     alphaTab_alphaSkia_NativeMethods
 * Method:    alphaskiaCanvasEndRotate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_NativeMethods_alphaskiaCanvasEndRotate
(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
