/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alphaTab_alphaSkia_AlphaSkiaData */

#ifndef _Included_alphaTab_alphaSkia_AlphaSkiaData
#define _Included_alphaTab_alphaSkia_AlphaSkiaData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaData
 * Method:    allocateCopy
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_alphaTab_alphaSkia_AlphaSkiaData_allocateCopy
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaData
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_alphaTab_alphaSkia_AlphaSkiaData_close
  (JNIEnv *, jobject);

/*
 * Class:     alphaTab_alphaSkia_AlphaSkiaData
 * Method:    toArray
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_alphaTab_alphaSkia_AlphaSkiaData_toArray
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
