on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y aptitude
      - run: sudo dpkg --add-architecture armhf
      - run: sudo sed -i "s/deb /deb [arch=amd64,i386] /" /etc/apt/sources.list
      - run: sudo sed -i "s/deb-src /deb-src [arch=amd64,i386] /" /etc/apt/sources.list
      - run: sudo su -c "echo 'deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ jammy main multiverse universe' >> /etc/apt/sources.list"
      - run: sudo su -c "echo 'deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ jammy-security main multiverse universe' >> /etc/apt/sources.list"
      - run: sudo su -c "echo 'deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ jammy-backports main multiverse universe' >> /etc/apt/sources.list"
      - run: sudo su -c "echo 'deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ jammy-updates main multiverse universe' >> /etc/apt/sources.list"
      - run: sudo apt-get update
      - run: sudo aptitude install -y crossbuild-essential-armhf libstdc++-11-dev-armhf-cross
      - run: sudo aptitude install -y aptitude install -y libfontconfig-dev:armhf libgl1-mesa-dev:armhf libglu1-mesa-dev:armhf freeglut3-dev:armhf
      - run: ls /usr
      - run: ls /usr/lib
      - run: ls /usr/lib/arm-linux-gnueabihf
      - run: ls /usr/arm-linux-gnueabihf/include

 