name: 'Build Skia'
description: 'Builds the Skia Native library'
inputs: 
  use-cache:
    description: 'Whether to try using the pre-compiled binary from the cache.'
    required: false
    default: 'false'
  architecture:
    description: 'The CPU architecture for which to build the lib'
    required: true
  variant:
    description: 'The library type to build'
    required: true
  target-os:
    description: 'The target Operating system identifier'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/cache/restore@v3
      if: ${{ inputs.use-cache }}
      with:
        path: dist
        restore-keys: alphaskia-${{ inputs.target-os }}-${{ inputs.architecture }}-${{ inputs.variant }}

    - run: ./build.cmd LibAlphaSkiaWithCache --target-os ${{ inputs.target-os }} --architecture ${{ inputs.architecture }} --variant ${{ inputs.variant }} --use-cache ${{ inputs.use-cache }}
    - uses: actions/upload-artifact@v3
      with:
        name: alphaskia-${{ inputs.target-os }}-${{ inputs.architecture }}-${{ inputs.variant }}
        path: artifacts

    - uses: actions/cache/save@v3
      with:
        path: dist
        key: alphaskia-${{ inputs.target-os }}-${{ inputs.architecture }}-${{ inputs.variant }}-${{ github.run_id }} 


