on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, x86, arm64]
        variant: ['shared', 'static']
        
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./build.cmd WindowsSkia --architecture ${{ matrix.architecture }} --variant ${{ matrix.variant }}
      - uses: actions/upload-artifact@v3
        with:
          name: alphaskia-windows-${{ matrix.architecture }}-${{ matrix.variant }}
          path: dist

  windows-jni:
    runs-on: windows-latest
    needs: [windows]
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, x86, arm64]
        
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./build.cmd WindowsJni --architecture ${{ matrix.architecture }} --variant ${{ matrix.variant }}
      - uses: actions/upload-artifact@v3
        with:
          name: alphaskia-windows-jni-${{ matrix.architecture }}-${{ matrix.variant }}
          path: dist

  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, x86, arm64]
        variant: ['shared', 'static']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./externals/skia/tools/install_dependencies.sh
      - run: ./build.sh Linux --architecture ${{ matrix.architecture }} --variant ${{ matrix.variant }}
      - uses: actions/upload-artifact@v3
        with:
          name: alphaskia-linux-${{ matrix.architecture }}-${{ matrix.variant }}
          path: dist

  linux-jni:
    runs-on: ubuntu-latest
    needs: [ubuntu]
    strategy:
      fail-fast: false
      matrix:
        # TODO architecture: [x64, x86, arm64]
        architecture: [x64]
        
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./build.cmd LinuxsJni --architecture ${{ matrix.architecture }} --variant ${{ matrix.variant }}
      - uses: actions/upload-artifact@v3
        with:
          name: alphaskia-linux-jni-${{ matrix.architecture }}-${{ matrix.variant }}
          path: dist

  dotnet:
    runs-on: windows-latest
    needs: [windows, linux]
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: dist
    - run: ./build.cmd DotNet
    - uses: actions/upload-artifact@v3
      with:
        name: Nupkgs
        path: |
          lib/dotnet/*/bin/Release/*.nukpg

  java:
    runs-on: ubuntu-latest
    needs: [windows-jni, linux-jni]
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: dist
    - run: ./build.cmd Java
    - uses: actions/upload-artifact@v3
      with:
        name: Jars
        path: |
          lib/java/main/build/libs/*.jar
          lib/java/linux/build/libs/*.jar
          lib/java/windows/build/libs/*.jar
