on:
  workflow_dispatch:
    inputs:
      use-skia-cache:
        type: boolean
        description: Use Skia Binary from cache
        default: false

jobs:

#
# Windows
  windows-skia:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, x86, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-skia
        with:
          use-cache: ${{ inputs.use-skia-cache }}
          architecture: ${{ matrix.architecture }}
          target-os: windows
  windows-alphaskia:
    runs-on: windows-latest
    needs: [windows-skia]
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, x86, arm64]
        variant: [shared, jni]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/build-alphaskia
        with:
          architecture: ${{ matrix.architecture }}
          variant: ${{ matrix.variant }}
          target-os: windows

#
# Linux
  linux-skia:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, x86, arm, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-skia
        with:
          use-cache: ${{ inputs.use-skia-cache }}
          architecture: ${{ matrix.architecture }}
          target-os: linux
  linux-alphaskia:
    runs-on: ubuntu-latest
    needs: [linux-skia]
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, x86, arm, arm64]
        variant: [shared, jni]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/build-alphaskia
        with:
          architecture: ${{ matrix.architecture }}
          variant: ${{ matrix.variant }}
          target-os: linux

#
# Android
  android-skia:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, x86, arm, arm64]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/build-skia
        with:
          use-cache: ${{ inputs.use-skia-cache }}
          architecture: ${{ matrix.architecture }}
          target-os: android
  android-alphaskia:
    runs-on: ubuntu-latest
    needs: [android-skia]
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, x86, arm, arm64]
        variant: [shared, jni]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/build-alphaskia
        with:
          architecture: ${{ matrix.architecture }}
          variant: ${{ matrix.variant }}
          target-os: android
#
# MacOs
  macos-skia:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-skia
        with:
          use-cache: ${{ inputs.use-skia-cache }}
          architecture: ${{ matrix.architecture }}
          target-os: macos
  macos-alphaskia:
    runs-on: macos-latest
    needs: [macos-skia]
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, arm64]
        variant: [shared, jni]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/build-alphaskia
        with:
          architecture: ${{ matrix.architecture }}
          variant: ${{ matrix.variant }}
          target-os: macos

#
# iOS
  ios-skia:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: arm64
            target-os: ios
          - architecture: arm64
            target-os: iossimulator
          - architecture: x64
            target-os: iossimulator
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-skia
        with:
          use-cache: ${{ inputs.use-skia-cache }}
          architecture: ${{ matrix.architecture }}
          target-os: ${{ matrix.target-os }}
  ios-alphaskia:
    runs-on: macos-latest
    needs: [ios-skia]
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: arm64
            variant: shared
            target-os: ios
          - architecture: arm64
            variant: shared
            target-os: iossimulator
          - architecture: x64
            variant: shared
            target-os: iossimulator
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/build-alphaskia
        with:
          architecture: ${{ matrix.architecture }}
          variant: ${{ matrix.variant }}
          target-os: ${{ matrix.target-os }}          
#
# Libraries
  dotnet:
    runs-on: windows-latest
    needs: [windows-alphaskia, linux-alphaskia, android-alphaskia, macos-alphaskia]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        path: dist
    - run: ./build.cmd DotNet
    - uses: actions/upload-artifact@v3
      with:
        name: Nupkgs
        path: |
          lib/dotnet/**/bin/Release/*.nupkg
          lib/dotnet/**/bin/Release/*.snupkg

  java:
    runs-on: ubuntu-latest
    needs: [windows-alphaskia, linux-alphaskia, android-alphaskia, macos-alphaskia, ios-alphaskia]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        path: dist
    - run: ./build.cmd Java
    - uses: actions/upload-artifact@v3
      with:
        name: Jars
        path: |
          lib/java/*/build/libs/*.jar
