on:
  workflow_dispatch:
    inputs:
      use-skia-cache:
        type: boolean
        description: Use Skia Binary from cache
        default: false

env:
  SONATYPE_SIGNING_KEY: ${{ secrets.SONATYPE_SIGNING_KEY }}
  SONATYPE_SIGNING_KEY_ID: ${{ secrets.SONATYPE_SIGNING_KEY_ID }}
  SONATYPE_SIGNING_PASSWORD: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
  SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
        

jobs:
  full_build:
    uses: .github/workflows/reusable-build.yaml
    with: 
      use-skia-cache: ${{ inputs.use-skia-cache }}
      alphaskia-version: 1.0
    secrets: inherit