on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, x86, arm64]
        variant: ['shared', 'static']
        
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./build.cmd WindowsSkia --architecture ${{ matrix.architecture }} --variant ${{ matrix.variant }}
      - uses: actions/upload-artifact@v3
        with:
          name: alphaskia-windows-${{ matrix.architecture }}-${{ matrix.variant }}
          path: artifacts

  windows-jni:
    runs-on: windows-latest
    needs: [windows]
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, x86, arm64]
        variant: ['shared']

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - run: ./build.cmd WindowsJni --architecture ${{ matrix.architecture }} --variant ${{ matrix.variant }}
      - uses: actions/upload-artifact@v3
        with:
          name: alphaskia-windows-jni-${{ matrix.architecture }}-${{ matrix.variant }}
          path: artifacts

  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64]
        # TODO architecture: [x64, x86, arm64]
        variant: ['shared', 'static']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./externals/skia/tools/install_dependencies.sh
      - run: ./build.sh LinuxSkia --architecture ${{ matrix.architecture }} --variant ${{ matrix.variant }}
      - uses: actions/upload-artifact@v3
        with:
          name: alphaskia-linux-${{ matrix.architecture }}-${{ matrix.variant }}
          path: artifacts

  linux-jni:
    runs-on: ubuntu-latest
    needs: [linux]
    strategy:
      fail-fast: false
      matrix:
        # TODO architecture: [x64, x86, arm64]
        architecture: [x64]
        variant: ['shared']

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - run: ./build.cmd LinuxJni --architecture ${{ matrix.architecture }} --variant ${{ matrix.variant }}
      - uses: actions/upload-artifact@v3
        with:
          name: alphaskia-linux-jni-${{ matrix.architecture }}-${{ matrix.variant }}
          path: artifacts

  android:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, x86, arm, arm64]
        variant: ['shared', 'static']

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./externals/skia/tools/install_dependencies.sh
      - run: ./build.sh AndroidSkia --architecture ${{ matrix.architecture }} --variant ${{ matrix.variant }}
      - uses: actions/upload-artifact@v3
        with:
          name: alphaskia-android-${{ matrix.architecture }}-${{ matrix.variant }}
          path: artifacts

  android-jni:
    runs-on: ubuntu-latest
    needs: [android]
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, x86, arm, arm64]
        variant: ['shared']

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - run: ./build.cmd AndroidJni --architecture ${{ matrix.architecture }} --variant ${{ matrix.variant }}
      - uses: actions/upload-artifact@v3
        with:
          name: alphaskia-android-jni-${{ matrix.architecture }}-${{ matrix.variant }}
          path: artifacts

  osx:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, arm64]
        variant: ['shared', 'static']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./build.sh OsxSkia --architecture ${{ matrix.architecture }} --variant ${{ matrix.variant }}
      - uses: actions/upload-artifact@v3
        with:
          name: alphaskia-osx-${{ matrix.architecture }}-${{ matrix.variant }}
          path: artifacts

  osx-jni:
    runs-on: macos-latest
    needs: [osx]
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, arm64]
        variant: ['shared', 'static']

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - run: ./build.cmd OsxJni --architecture ${{ matrix.architecture }} --variant ${{ matrix.variant }}
      - uses: actions/upload-artifact@v3
        with:
          name: alphaskia-osx-jni-${{ matrix.architecture }}-${{ matrix.variant }}
          path: artifacts

  dotnet:
    runs-on: windows-latest
    needs: [windows, linux]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - uses: actions/download-artifact@v3
      with:
        path: dist
    - run: ./build.cmd DotNet
    - uses: actions/upload-artifact@v3
      with:
        name: Nupkgs
        path: |
          lib/dotnet/**/bin/Release/*.nupkg
          lib/dotnet/**/bin/Release/*.snupkg

  java:
    runs-on: ubuntu-latest
    needs: [windows-jni, linux-jni, android-jni]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - uses: actions/download-artifact@v3
      with:
        path: dist
    - run: ./build.cmd Java
    - uses: actions/upload-artifact@v3
      with:
        name: Jars
        path: |
          lib/java/main/build/libs/*.jar
          lib/java/linux/build/libs/*.jar
          lib/java/android/build/libs/*.jar
          lib/java/windows/build/libs/*.jar
