on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [WindowsX64, WindowsX86, WindowsArm64]
    steps:
      - uses: actions/checkout@v3
      - run: nuke ${{ matrix.target }}
