on:
  workflow_dispatch:
    inputs:
      is-release-build:
        type: boolean
        description: Whether the version is a prerelease or full release
        default: false
env:
  NPMJS_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  SONATYPE_SIGNING_KEY: ${{ secrets.SONATYPE_SIGNING_KEY }}
  SONATYPE_SIGNING_KEY_ID: ${{ secrets.SONATYPE_SIGNING_KEY_ID }}
  SONATYPE_SIGNING_PASSWORD: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
  SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

jobs:
  build:
    uses: .github/workflows/reusable-build.yaml
    with: 
      # TODO: change to false once pipeline is done
      use-skia-cache: true 
      alphaskia-version: 1.0.0.${{ github.run_number }}
      is-release-build: ${{ inputs.is-release-build }}
    secrets: inherit

  dotnet-publish: 
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: nodetars
          path: dist/.organize/node
      - run: ./build.sh DotNetPublish

  java-publish: 
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: maven
          path: dist/.organize/maven
      - run: ./build.sh JavaPublish

  node-publish: 
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: nodetars
          path: dist/.organize/node
      - run: ./build.sh NodePublish