on:
  workflow_dispatch:

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install crossbuild-essential-i386 crossbuild-essential-armhf crossbuild-essential-arm64
      - run: sudo apt-get install gcc-multilib g++-multilib
      - run: |
          ls -l /usr/aarch64-linux-gnu
          ls -l /usr/aarch64-linux-gnu/bin
          ls -l /usr/aarch64-linux-gnu/lib
          ls -l /usr/aarch64-linux-gnu/include
          ls -l /usr/aarch64-linux-gnu/include/c++/
          ls -l /usr/aarch64-linux-gnu/include/c++/11/
          echo OK

      - run: |
          ls -l /usr/arm-linux-gnueabihf
          ls -l /usr/arm-linux-gnueabihf/bin
          ls -l /usr/arm-linux-gnueabihf/lib
          ls -l /usr/arm-linux-gnueabihf/include
          ls -l /usr/arm-linux-gnueabihf/include/c++/
          ls -l /usr/arm-linux-gnueabihf/include/c++/11/
          echo OK

      - run: |
          ls -l /usr/i686-linux-gnu
          ls -l /usr/i686-linux-gnu/bin
          ls -l /usr/i686-linux-gnu/lib
          ls -l /usr/i686-linux-gnu/include
          ls -l /usr/i686-linux-gnu/include/c++/
          ls -l /usr/i686-linux-gnu/include/c++/11/
          echo OK

      - run: sudo dpkg --add-architecture armhf
      - run: sudo dpkg --add-architecture arm64
      - run: sudo dpkg --add-architecture i386
      # Limit current sources to amd64
      - run: sudo sed -i "s/deb/deb [arch=amd64]/" /etc/apt/sources.list
      - run: sudo cat /etc/apt/sources.list
      # Add other archs from ports.ubuntu.com
      - run: sudo echo 'deb [arch=i386,arm64,armhf] http://ports.ubuntu.com/ubuntu-ports jammy main universe' >> /etc/apt/sources.list
      - run: sudo echo 'deb-src [arch=i386,arm64,armhf] http://ports.ubuntu.com/ubuntu-ports jammy main universe' >> /etc/apt/sources.list
      - run: sudo apt-get update
      
      - run: sudo apt-get install libfontconfig-dev:armhf
      - run: sudo apt-get install libfontconfig-dev:arm64
      - run: sudo apt-get install libfontconfig-dev:i386
