on:
  workflow_dispatch:

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - run: apt-get update
      - run: apt-get install -y crossbuild-essential-i386 crossbuild-essential-armhf crossbuild-essential-arm64
      - run: apt-get install -y gcc-multilib g++-multilib
      - run: |
          ls -l /usr/aarch64-linux-gnu
          ls -l /usr/aarch64-linux-gnu/bin
          ls -l /usr/aarch64-linux-gnu/lib
          ls -l /usr/aarch64-linux-gnu/include
          ls -l /usr/aarch64-linux-gnu/include/c++/
          ls -l /usr/aarch64-linux-gnu/include/c++/12/
          echo OK

      - run: |
          ls -l /usr/arm-linux-gnueabihf
          ls -l /usr/arm-linux-gnueabihf/bin
          ls -l /usr/arm-linux-gnueabihf/lib
          ls -l /usr/arm-linux-gnueabihf/include
          ls -l /usr/arm-linux-gnueabihf/include/c++/
          ls -l /usr/arm-linux-gnueabihf/include/c++/12/
          echo OK

      - run: |
          ls -l /usr/i686-linux-gnu
          ls -l /usr/i686-linux-gnu/bin
          ls -l /usr/i686-linux-gnu/lib
          ls -l /usr/i686-linux-gnu/include
          ls -l /usr/i686-linux-gnu/include/c++/
          ls -l /usr/i686-linux-gnu/include/c++/13/
          echo OK

      - run: dpkg --add-architecture armhf
      - run: dpkg --add-architecture arm64
      - run: dpkg --add-architecture i386
      # - run: cat /'deb [arch=i386,arm64,armhf] mirror+file:/etc/apt/apt-mirrors.txt jammy main universe' >> /etc/apt/sources.list
      - run: apt-get update
      
      - run: apt-get install -y libfontconfig-dev:armhf
      - run: apt-get install -y libfontconfig-dev:arm64
      - run: apt-get install -y libfontconfig-dev:i386