on:
  workflow_call:
    inputs:
      # Versioning
      alphaskia-version:
        type: string
        description: The version for alphaSkia in format MAJOR.MINOR
        required: true
      is-release-build:
        type: boolean
        description: Whether the version is a prerelease or full release
        required: false

env:
  ALPHASKIA_VERSION_TEMPLATE: ${{ inputs.alphaskia-version }}
  IS_RELEASE_BUILD: ${{ inputs.is-release-build }}

jobs:
  dotnet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8'
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: nuke
        path: build/bin/Debug/publish/
    - uses: actions/download-artifact@v3
      with:
        path: dist/.organize
    - run: ./build.cmd DotNet
    - uses: actions/upload-artifact@v3
      with:
        name: nupkgs
        path: |
          lib/dotnet/**/*.nupkg
  dotnet-test:
    strategy:
      fail-fast: false
      matrix:
        include: 
          - runs-on: ubuntu-latest
            architecture: x64
            framework: net8.0
          - runs-on: macos-latest
            architecture: x64
            framework: net8.0
          - runs-on: windows-latest
            architecture: x64
            framework: net8.0
          - runs-on: windows-latest
            architecture: x64
            framework: net48
    runs-on: ${{ matrix.runs-on }}
    needs: [dotnet]
    steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8'      
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: nupkgs
        path: dist/.organize/nupkgs
    - run: ./build.cmd DotNetTest --architecture ${{ matrix.architecture }} --framework ${{ matrix.framework }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: dotnettest-${{ matrix.runs-on }}-${{ matrix.architecture }}--${{ matrix.framework  }}
        path: |
          test/test-outputs/**/*.*
